version: '3'
services:
    trainer:
        build: trainer/
        volumes:
        - ./models:/app/models
        depends_on:
          - model_api
    
    model_api:
        build: model_api/
        volumes:
        - ./models:/app/models
        ports:
          - "4242:80"
